Improve install/remove messages

diff --git a/:za-linkman-atclone-handler b/:za-linkman-atclone-handler
--- a/:za-linkman-atclone-handler
+++ b/:za-linkman-atclone-handler
@@ -10,21 +10,27 @@ if [[ "$1" = plugin ]] {
 }
 
 if (( ${+ICE[lman]} )) {
+    [[ -d ${ZPFX}/man/man1 ]] || \
+        { print -P -- "%F{38}linkman annex: %F{160}Missing ${ZPFX}/man/man1, not installing man pages%f" && return}
     local manfiles=${dir}/**/*.1(.)
-    local manfile installed
+    declare -a manfile installed attempted failed
     for manfile ( $~manfiles ); do
-        (( ${installed[(I)$manfile:t]} )) && continue
-        installed+=( $manfile:t )
-        { test -f $manfile && [[ -d ${ZPFX}/man/man1 ]] } && {
-                    (( !OPTS[opt_-q,--quiet] )) && \
-                        print -P -- "%F{38}linkman annex: %F{154}Installed man page: %F{219}$manfile:t%f"
-                    command ln -f -- $manfile ${ZPFX}/man/man1
-                } || {
-                    (( !OPTS[opt_-q,--quiet] )) && \
-                        print -P -- "%F{38}linkman annex: %F{160}Could not install man page%f"
-                }
+        (( ${attempted[(I)$manfile:t]} )) && continue
+        attempted+=( $manfile:t )
+        { test -f $manfile } && {
+            installed+=( "%F{219}$manfile:t" )
+            command ln -f -- $manfile ${ZPFX}/man/man1
+        } || {
+            failed+=( "%F{219}$manfile:t" )
+        }
     done
+    (( !OPTS[opt_-q,--quiet] )) && {
+        (( ${#installed} )) && \
+            print -P -- "%F{38}linkman annex: %F{154}Installed man page${${${#installed}/1/}:+s}: ${(j:%f, :)installed}%f"
+        (( ${#failed} )) && \
+            print -P -- "%F{38}linkman annex: %F{160}Could not install man page${${${#failed}/1/}:+s}: ${(j:%f, :)failed}%f"
     }
+}
 
 }
 
